openapi: 3.0.1
info:
  title: School Timetabling API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a hello message
      description: A simple endpoint to test the API
      tags:
        - Hello Resource
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: hello
